spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create  # ? ????? None ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath*:data.sql
logging:
  config: classpath:logback-spring.xml
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: admin@email.com

jwt:
  secret-key: test12345test12345test12345test12345test12345test12345test12345
  access-token-expiration-minutes: 180
  refresh-token-expiration-minutes: 420

toss:
  test:
    secret-api-key: test_sk_P24xLea5zVAPgGnNPdb3QAMYNwW6
    origin-url: https://api.tosspayments.com/v1
    success-url: http://localhost:8080/payments/success
    fail-url: http://localhost:8080/payments/fail
cloud:
  aws:
    credentials:
      access-key: AKIATHBNGYVRJKFVAZ43
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    s3:
      bucket: culinari-images
