spring:
  datasource:
    url: jdbc:mysql://database-1.cktr7ur61tsd.ap-northeast-2.rds.amazonaws.com:13305/culinari
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: asdfqwer1234

  jpa:
    hibernate:
      ddl-auto: none  # ? ????? None ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
#    defer-datasource-initialization: false
logging:
  config: classpath:logback-spring.xml
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: admin@email.com

jwt:
  secret-key: test12345test12345test12345test12345test12345test12345test12345
  access-token-expiration-minutes: 180
  refresh-token-expiration-minutes: 420

toss:
  test:
    secret-api-key: test_sk_P24xLea5zVAPgGnNPdb3QAMYNwW6
    origin-url: https://api.tosspayments.com/v1
    success-url: http://3.37.105.24:8080/payments/success
    fail-url: http://3.37.105.24:8080/payments/fail

cloud:
  aws:
    credentials:
      access-key: AKIATHBNGYVRJKFVAZ43
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    s3:
      bucket: culinari-images
